<!DOCTYPE html>
<html>
	<head>
		<meta charset = "utf-8"/>
		<link rel="stylesheet" href="../css/style.css"/>
	</head>
	<body class="page-body">	
		<?php echo $header;?>
		<div class="empty  empty--margin-30"></div>
		<form name="auth" class="auth-form" method="POST" action="/auth">
			<div class="auth-form__title">Авторизация</div>
			<input name="login" type="text" class="auth-form__field  auth-form__field--type-user"/>
			<input name="password" type="password" class="auth-form__field  auth-form__field--type-password"/>
			<div class="auth-form__field  btn btn--color-yellow auth-form__field--type-submit" onclick='document.getElementsByClassName("auth-form")[0].submit();'>
			Войти
			</div>	
		</form>
		<script>
			window.addEventListener('keydown', function(e){
				var key = e.which || e.keyCode;
				if (key == 13) {
					document.getElementsByClassName("auth-form")[0].submit();
				}
			});
		</script>
	</body>
</html>