<!DOCTYPE html>
<html>
	<head>
		<meta charset = "utf-8"/>
		<link rel="stylesheet" href="css/style.css"/>
	</head>
	<body class="page-body">	
		<header class="page-header">
			<div class="page-header__logo-wrapper">
				<div class="page-header__logo"></div>
				<div class="page-header__title">Глобальные настройки</div>
			</div>	
		</header>
		<div class="empty  empty--margin-30"></div>
		<div class="popup">
			<div class="info-form">
				<div class="info-form__content">
					<div class="info-form__icon  info-form__icon--delete"></div>
					<div class="info-form__text">Вы действительно хотите удалить элемент?</div>
				</div>
				<div class="empty  empty--margin-30"></div>
				<div class="info-form__buttons">
					<div class="info-form__btn  new-user-form__btn  btn  btn--color-yellow">ОК</div>	
					<div class="info-form__btn  new-user-form__btn  btn  btn--color-yellow">Отмена</div>
				</div>
			</div>
		</div>
	</body>
</html>