<!DOCTYPE html>
<html>
	<head>
		<meta charset = "utf-8"/>
		<link rel="stylesheet" href="css/style.css"/>
	</head>
	<body class="page-body">	
		<header class="page-header">
			<div class="page-header__logo-wrapper">
				<div class="page-header__logo"></div>
				<div class="page-header__title">Глобальные настройки</div>
			</div>	
		</header>
		<div class="empty  empty--margin-30"></div>
		<div class="popup">
			<div class="new-user-form">
				<div class="new-user-form__title">Новый пользователь БД</div>
				<div class="new-user-form__item">
					<label class="new-user-form__label">Имя пользователя:</label>
					<input name="login" type="text" class="new-user-form__input"/>
				</div>
				<div class="new-user-form__item">
					<label class="new-user-form__label">Новый пароль:</label>
					<input name="password" type="password" class="new-user-form__input"/>
				</div>
				<div class="new-user-form__item">
					<label class="new-user-form__label">Повторите пароль:</label>
					<input name="repassword" type="password" class="new-user-form__input"/>
				</div>
				<div class="empty  empty--margin-30"></div>
				<div class="new-user-form__buttons">
					<div class="new-user-form__btn  btn  btn--color-yellow">ОК</div>	
					<div class="new-user-form__btn  btn  btn--color-yellow">Отмена</div>
				</div>
			</div>
		</div>
	</body>
</html>