<!DOCTYPE html>
<html>
	<head>
		<meta charset = "utf-8"/>
		<link rel="stylesheet" href="css/style.css"/>
	</head>
	<body class="page-body">	
		<?php echo $header;?>
		<div class="empty  empty--margin-30"></div>
		<div class="settings-menu  settings-menu--active  settings-menu--theme-main">
			<div class="settings-menu__item  settings-menu__item--theme-server">Для сервера</div>
			<div class="settings-menu__item  settings-menu__item--theme-pc">Для компьютеров</div>
			<div class="settings-menu__item  settings-menu__item--theme-user">Для пользователей</div>
			<div class="settings-menu__item  settings-menu__item--theme-group">Группы</div>
		</div>
		<div class="settings-menu  settings-menu--theme-server  settings-menu--active">
			<div class="settings-menu__header">Общие настройки</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Общие настройки</div>
			<div class="settings-menu__header">Мониторинг</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Снимки экранов</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Веб-камеры</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Автопрослушка</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Теневое копирование</div>
			<div class="settings-menu__header  ">Генератор отчетов</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Параметры</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Типы отчетов</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Сохранение в папку</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Отправка по FTP</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Отправка на e-mail</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Отправка на веб-сайт</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Угрозы</div>
			<div class="settings-menu__header  ">Генератор уведомлений</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Отправка на e-mail</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Отправка по SMS</div>
		</div>
		<div class="settings-menu  settings-menu--theme-pc">
			<div class="settings-menu__header">Общие настройки</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Общие настройки</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Выборочное наблюдение</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Локальное хранилище</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Запреты</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">События</div>
			<div class="settings-menu__header">Мониторинг</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Машинное время</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Веб-камеры</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Автопрослушка</div>
			<div class="settings-menu__item  settings-menu__item--theme-menu">Контроль оборудования</div>			
		</div>
		<?php echo $footer;?>
	</body>
</html>